// SPDX-License-Identifier: MIT
// Generated by work/generate_vault_schema.py from shared/0001.sql; do not edit.
package org.capybaragram.local;

final class VaultSchema {
    static final String[] STATEMENTS = {
        "CREATE TABLE notes (\n    id INTEGER PRIMARY KEY,\n    peer_type TEXT NOT NULL CHECK (peer_type IN ('user','chat','channel')),\n    peer_id INTEGER NOT NULL CHECK (typeof(peer_id)='integer' AND peer_id>0),\n    topic_id INTEGER NOT NULL DEFAULT 0\n        CHECK (typeof(topic_id)='integer' AND topic_id>=0),\n    payload BLOB NOT NULL\n        CHECK (typeof(payload)='blob' AND length(payload)>=1 AND length(payload)<=131072),\n    created_at INTEGER NOT NULL CHECK (typeof(created_at)='integer' AND created_at>=0),\n    updated_at INTEGER NOT NULL CHECK (typeof(updated_at)='integer' AND updated_at>=created_at),\n    CHECK (topic_id=0 OR peer_type='channel'),\n    UNIQUE (peer_type,peer_id,topic_id)\n)",
        "CREATE TABLE templates (\n    id INTEGER PRIMARY KEY,\n    payload BLOB NOT NULL\n        CHECK (typeof(payload)='blob' AND length(payload)>=1 AND length(payload)<=131072),\n    sort_order INTEGER NOT NULL DEFAULT 0\n        CHECK (typeof(sort_order)='integer' AND sort_order>=0),\n    created_at INTEGER NOT NULL CHECK (typeof(created_at)='integer' AND created_at>=0),\n    updated_at INTEGER NOT NULL CHECK (typeof(updated_at)='integer' AND updated_at>=created_at)\n)",
        "CREATE INDEX templates_sort_order_idx ON templates(sort_order,id)"
    };
    private VaultSchema() {}
}
